// Test editor data flows without requiring a browser or a network service.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..'),nodes=new Map();
const document={addEventListener(){},getElementById(id){
  if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',hidden:false,value:''});
  return nodes.get(id);
}};
const context={document,window:{},sessionStorage:{getItem(){return null},setItem(){}}};
context.window=context;vm.createContext(context);
for(const name of ['defaults','baselines','units','validation','calculations-weight','calculations-loads',
  'calculations-spar','calculations-optimization','feasibility','sensitivity','optimization-ui','export','app','baseline-editor','aircraft-geometry']){
  vm.runInContext(fs.readFileSync(path.join(root,'js',name+'.js'),'utf8'),context,{filename:name+'.js'});
}
const A=context.AST,base=JSON.parse(fs.readFileSync(path.join(root,'data/baselines/inha_2prop.json')));
const provenance=A.clone(base);
provenance.structural_inputs.material.krw={value:1.2,unit:'1',source_type:'ASSUMED',source_note:'Inherited; verify',inherited_from:'prior r1'};
A.editorDraft=provenance;
const form=nodes.get('baselineForm')||document.getElementById('baselineForm');
form.elements=Object.fromEntries(['id','school','concept_name','configuration','source','notes'].map(key=>[key,{value:provenance[key]}]));
form.elements.active={checked:true};form.elements.design_source={value:'ultimate'};
form.querySelector=selector=>{
  const [,kind,path]=selector.match(/\[data-editor-(value|source|note)="([^"]+)"\]/);
  const field=A.editorGet(provenance,path);
  return {value:kind==='value'?field?.value==null?'':String(field.value):kind==='source'?field?.source_type||'ASSUMED':field?.source_note||''};
};
const unchanged=A.collectBaselineEditor();
assert.equal(JSON.stringify(unchanged.structural_inputs.material.krw),JSON.stringify(provenance.structural_inputs.material.krw),'unchanged units and inherited provenance must survive editing');
assert.equal(unchanged.structural_inputs.design.source,undefined,'editing an unrelated field does not invent a load source');
const mine=A.clone(base),latest=A.clone(base);
mine.battery.capacity_Ah.value=4;
mine.wing.area.value=.9;
mine.notes='내 메모';
latest.battery.capacity_Ah.value=5;
latest.flight.speed.value=28;
latest.notes='다른 팀원 메모';latest.revision=2;
const merge=A.mergeBaselineChanges(base,mine,latest);
assert.equal(merge.merged.revision,2);
assert.equal(merge.merged.wing.area.value,.9,'nonoverlapping local edits survive');
assert.equal(merge.merged.flight.speed.value,28,'nonoverlapping server edits survive');
assert.deepEqual(Array.from(merge.conflicts,c=>c.path).sort(),['battery.capacity_Ah','notes']);
assert.equal(merge.conflicts.find(c=>c.path==='battery.capacity_Ah').mine.value,4);
const removed=A.clone(base);delete removed.wing.taper;
assert.equal(A.mergeBaselineChanges(base,removed,latest).merged.wing.taper,undefined,'field deletions survive a merge');
const sourceOnly=A.clone(base),otherSource=A.clone(base);
sourceOnly.wing.area.source_note='새 근거';otherSource.wing.area.source_note='다른 근거';
assert.equal(A.mergeBaselineChanges(base,sourceOnly,otherSource).conflicts[0].path,'wing.area','provenance conflicts also require review');

const initial=A.baselineToState(base).state;
let downloaded;
A.download=(name,content)=>{downloaded={name,content};};
A.exportJSON(initial);
const imported=A.sanitizeImported(JSON.parse(downloaded.content));
assert.equal(imported.battery.series_count,12);
assert.equal(imported.battery.capacity_Ah,3.3);
assert.equal(imported.propulsion.prop_count,2);
assert.equal(imported.weightBudget.battery,null);
assert.equal(imported.baselineReference.id,base.id);
assert.equal(imported.presetLocked,false,'imported working inputs never edit the source baseline');
const legacy=A.clone(initial);delete legacy.battery;delete legacy.propulsion;delete legacy.baselineReference;
assert.equal(A.sanitizeImported(legacy).weightBudget.battery,null,'legacy saved inputs remain supported');

const working=A.clone(initial);working.weightBudget.battery=1.2;
working.battery.capacity_Ah=4;working.sources['weightBudget.battery']='STRUCT';
A.activeBaseline=base;A.state=working;
const r=A.calculate(working);
A.exportCSV(r);
assert.ok(downloaded.content.includes('"배터리 질량","1.2","kg","STRUCT"'));
assert.ok(downloaded.content.includes('"배터리 용량","4","Ah"'));
A.exportText(r);
assert.ok(downloaded.content.includes('12S 4 Ah · 배터리 질량 1.2 kg'));
A.renderBaselineBar();
assert.ok(nodes.get('baselineMeta').textContent.includes('1.2 kg'));
assert.equal(base.battery.battery_mass_kg.value,null,'working edits do not mutate baseline JSON');
const svg=A.sparSectionSVG(r,r.optimization.provisional);
assert.ok(svg.includes('Conceptual NACA4 section based on t/c'));
assert.ok(r.optimization.provisional.rootSelectedCapAreaMm2>=r.optimization.provisional.rootStiffnessCapAreaMm2);

let builds=0,renders=0;
A.buildInputs=()=>{builds++;};
A.render=()=>{renders++;A.lastResult=A.calculate(A.state);};
A.baselines=[base];
A.selectedCandidateIndex=18;
A.setActiveBaseline(base);
assert.equal(A.selectedCandidateIndex,undefined);
const first=A.lastResult;
const alternative=A.duplicateBaselineData(base);
alternative.id='new_concept';alternative.school='KAU';alternative.concept_name='4-Prop';
alternative.propulsion.prop_count.value=4;
alternative.wing.area.value=.9;alternative.wing.ar.value=10;
alternative.aircraft.mass.value=20;
alternative.battery.battery_mass_kg.value=1.1;alternative.battery.battery_mass_kg.source_type='STRUCT';
delete alternative.flight.speed;
A.setActiveBaseline(alternative);
assert.equal(builds,2);assert.equal(renders,2);
assert.equal(A.lastResult.state.flight.speed,A.defaults.flight.speed,'previous concept speed is cleared');
assert.equal(A.lastResult.state.battery.capacity_Ah,3.3);
assert.equal(A.lastResult.state.weightBudget.battery,1.1);
assert.equal(A.geometry(A.lastResult.state).motors.length,4);
assert.notEqual(A.lastResult.weight.raymerWing,first.weight.raymerWing);
assert.notEqual(A.lastResult.loads.ultimate,first.loads.ultimate);
assert.notEqual(A.lastResult.spar.rootMoment,first.spar.rootMoment);
assert.notEqual(A.lastResult.optimization.empiricalWingMassKg,first.optimization.empiricalWingMassKg);
assert.equal(A.lastResult.errors.length,0);
const single=A.clone(A.lastResult.state);single.propulsion.prop_count=1;
assert.equal(A.geometry(single).motors.length,1);
assert.equal(A.geometry(single).motors[0].y,0);
const both=A.clone(base);both.wing.span={value:1.5,unit:'m',source_type:'INHA',source_note:'reported'};
const inconsistent=A.baselineToState(both).state;
assert.equal(inconsistent.wing.span,1.5,'reported physical span is used when both span and AR are supplied');
assert.ok(A.geometryChecks(inconsistent).some(check=>check.warning&&check.name.includes('보고 AR')));

(async()=>{
  context.fetch=async url=>({ok:url!=='api/config',json:async()=>url.endsWith('manifest.json')?{baselines:['inha_2prop.json']}:base});
  await A.fetchBaselines();
  assert.equal(A.editorMode,false,'GitHub Pages has no config API and stays public');
  assert.equal(nodes.get('baselineEditorActions').hidden,true);
  assert.equal(A.baselines.length,1);
  context.fetch=async url=>({ok:true,json:async()=>url==='api/config'?{mode:'EDITOR_MODE'}:[base,alternative]});
  await A.fetchBaselines();
  assert.equal(A.editorMode,true);
  assert.equal(nodes.get('baselineEditorActions').hidden,false);
  assert.equal(A.baselines.length,2);
  const saved=A.clone(base);saved.revision=2;saved.battery.capacity_Ah.value=4;
  A.fetchBaselines=async()=>{throw Error('temporary list failure');};
  await A.applySavedBaseline(saved,'r2 저장 · Local Git committed');
  assert.equal(A.activeBaseline.revision,2);
  assert.equal(A.lastResult.state.battery.capacity_Ah,4,'successful save recalculates even if list refresh fails');
  assert.ok(nodes.get('presetStatus').textContent.includes('r2 저장'));
  assert.ok(nodes.get('presetStatus').textContent.includes('목록 갱신 실패'));
  console.log('Baseline editor, merge, export and mode tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
